import NavbarHome from '@/components/NavbarHome'
import './globals.css'
import { Inter } from 'next/font/google'
import Foother from '@/components/Foother'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarHome/>
        {children}
        <Foother/>
        </body>
    </html>
  )
}
